"""Update document table and add document_chunks table

Revision ID: 2ef7501b8f3c
Revises: 6e4830d17465
Create Date: 2025-07-17 01:28:28.759302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ef7501b8f3c'
down_revision: Union[str, None] = '6e4830d17465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('agents', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('document_chunks', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('document_chunks', sa.Column('embedding_status', sa.String(length=20), nullable=False))
    op.add_column('document_chunks', sa.Column('num_tokens', sa.Integer(), nullable=False))
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('document_chunks', 'chunk_index')
    op.drop_column('document_chunks', 'vector_id')
    op.drop_column('document_chunks', 'chunk_text')
    op.add_column('documents', sa.Column('processing_status', sa.String(length=20), nullable=False))
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('doc_type', sa.String(length=50), nullable=True))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'metadata')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'file_size')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('documents', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('documents', 'doc_type')
    op.drop_column('documents', 'summary')
    op.drop_column('documents', 'processing_status')
    op.add_column('document_chunks', sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('document_chunks', sa.Column('vector_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('document_chunks', sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('document_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('document_chunks', 'num_tokens')
    op.drop_column('document_chunks', 'embedding_status')
    op.drop_column('document_chunks', 'content')
    op.alter_column('chat_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
