"""Update models to use timezone-aware datetimes

Revision ID: d3f92ea9645e
Revises: b3c64bfe60e1
Create Date: 2025-07-09 18:07:09.297947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3f92ea9645e"
down_revision: Union[str, None] = "b3c64bfe60e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
