# This file is auto-generated by setuptools-scm
from typing import Optional, Tuple, Union

__version__: str = "0.1.0"  # This will be replaced by setuptools_scm
__version_tuple__: Tuple[Union[int, str], ...] = (0, 1, 0)  # This will be replaced by setuptools_scm

def version_tuple() -> Tuple[Union[int, str], ...]:
    """Return version as a tuple for comparisons."""
    return __version_tuple__

__all__ = ["__version__", "__version_tuple__", "version_tuple"]
